"""Publish generated screenshot PNGs to a dedicated GitHub branch.

The workflow captures screenshots into a local directory, then this script commits
those PNGs to a persistent branch so PR comments can embed stable image URLs.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import tempfile
from pathlib import Path


def run(*args: str, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(args, check=check, text=True)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--pr-number", required=True)
    parser.add_argument("--screenshots-dir", default="screenshots")
    parser.add_argument("--branch", default="site-screenshots")
    args = parser.parse_args()

    screenshots_dir = Path(args.screenshots_dir)
    desktop = screenshots_dir / "desktop.png"
    mobile = screenshots_dir / "mobile.png"
    if not desktop.is_file() or not mobile.is_file():
        raise SystemExit("Expected screenshots/desktop.png and screenshots/mobile.png")

    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        desktop_tmp = tmp_path / "desktop.png"
        mobile_tmp = tmp_path / "mobile.png"
        shutil.copy2(desktop, desktop_tmp)
        shutil.copy2(mobile, mobile_tmp)

        run("git", "config", "user.name", "github-actions[bot]")
        run("git", "config", "user.email", "41898282+github-actions[bot]@users.noreply.github.com")
        run("git", "fetch", "origin", args.branch, check=False)

        remote_ref = f"refs/remotes/origin/{args.branch}"
        exists = run("git", "show-ref", "--verify", "--quiet", remote_ref, check=False).returncode == 0
        if exists:
            run("git", "switch", "--force-create", args.branch, remote_ref)
        else:
            run("git", "switch", "--orphan", args.branch)
            run("git", "rm", "-rf", ".", check=False)

        target = Path(f"pr-{args.pr_number}")
        target.mkdir(parents=True, exist_ok=True)
        shutil.copy2(desktop_tmp, target / "desktop.png")
        shutil.copy2(mobile_tmp, target / "mobile.png")
        Path("README.md").write_text("Screenshots generated by GitHub Actions.\n", encoding="utf-8")

        run("git", "add", "README.md", str(target / "desktop.png"), str(target / "mobile.png"))
        committed = run("git", "commit", "-m", f"Update screenshots for PR {args.pr_number}", check=False).returncode == 0
        if committed:
            run("git", "push", "origin", args.branch)
        else:
            print("No screenshot changes to commit.")


if __name__ == "__main__":
    main()
